---
# tasks file for ansible-role-passenger-nginx

- name: Ensure needed APT packages are present
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - dirmngr
      - gnupg
      - gnupg2
      - lsb-release
      - ubuntu-keyring
    state: present

- name: Ensure Passenger APT key is present
  shell:
    cmd: curl https://oss-binaries.phusionpassenger.com/auto-software-signing-gpg-key.txt | gpg --dearmor | tee /usr/share/keyrings/phusion-passenger.gpg >/dev/null
  changed_when: false

- name: Ensure Passenger APT repo is configured
  apt_repository:
    repo: >
      deb [signed-by=/usr/share/keyrings/phusion-passenger.gpg] https://oss-binaries.phusionpassenger.com/apt/passenger
      {{ ansible_distribution_release }} main
    state: present
    update_cache: true

- name: Ensure Nginx and Passenger are present
  apt:
    name:
      - nginx
      - libnginx-mod-http-passenger
      - libnginx-mod-http-headers-more-filter
    state: present

- name: Ensure passenger module is enabled
  file:
    src: /usr/share/nginx/modules-available/mod-http-passenger.load
    dest: /etc/nginx/modules-enabled/50-mod-http-passenger.conf
    state: link

- name: Ensure headers_more module is enabled
  file:
    src: /usr/share/nginx/modules-available/mod-http-headers-more-filter.conf
    dest: /etc/nginx/modules-enabled/50-mod-http-headers-more-filter.conf
    state: link

- name: Ensure passenger config file is updated
  template:
    src: mod-http-passenger.conf.j2
    dest: /etc/nginx/conf.d/mod-http-passenger.conf
  notify: restart nginx

- name: Ensure NGINX config file is updated
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Configure the NGINX virtual host
  copy:
    dest: /etc/nginx/sites-enabled/default
    content: "{{ nginx_vhost_config }}"
  notify: restart nginx
