---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Ensure ruby is present
      apt:
        name: ruby-full
        update_cache: true
  roles:
    - role: ansible-role-passenger-nginx
      nginx_user: www-data www-data
      nginx_server_name: www.example.com
      passenger_extra_config: |
        passenger_max_pool_size 6;
        passenger_min_instances 6;
        passenger_pre_start {{ nginx_server_name }};
      nginx_extra_config: |
        worker_rlimit_nofile 8192;
      nginx_events_extra_config: |
        multi_accept on;
      nginx_http_extra_config: |
        # Hide nginx version information.
        server_tokens off;
        server_names_hash_bucket_size 128;
        proxy_hide_header X-Powered-By;
      nginx_vhost_config: |
        server {
          listen 80 default_server;
          server_name {{ nginx_server_name }};
          root {{ passenger_app_root }};

          location @rubyapp {
            passenger_enabled on;
            passenger_app_env {{ passenger_app_env }};
          }

          location / {
            try_files $uri $uri/index.html @rubyapp;
          }
        }
